Hw10
ObeyMeee/nix pull request #1
Opened 2022-07-09 12:01 UTC by ObeyMeee

2022-07-09 20:05 UTC, Fabolo12 requested changes
У тебя версия проекта стоит 1.7, да и нет части зависимостей, код невозможно скомпилировать

2022-07-10 19:46 UTC, Fabolo12 approved these changes

2022-07-10 19:46 UTC, Fabolo12 commented on pom.xml
> +        <maven.compiler.target>1.7</maven.compiler.target>
Почему все еще 1.7, минимум 8 должна быть

2022-07-10 19:46 UTC, Fabolo12 commented on pom.xml
> +                    <target>8</target>
При этом тут 8)

2022-07-11 03:40 UTC, ObeyMeee commented on pom.xml
> +        <maven.compiler.target>1.7</maven.compiler.target>
да,это мавен наверное так генерирует по дефолту, В следующем коммите обновил это,странно,потому что у меня стоит jdk 17

2022-07-15 06:05 UTC, merged